### ISSUE TITLE
Didn't safe error handling

### ISSUE THREAD

**Issue by lueurxax** [PavelVershinin/xtpl#1]
https://github.com/PavelVershinin/xtpl/blob/6c6bc01b40101a6e0bb0372f8baecdcc8940755f/xtpl.go#L27

**Comment by PavelVershinin** [comment]
Please excuse me, but I don't see a problem

**Comment by oripio** [comment]
@PavelVershinin Let me please explain, @lueurxax just polite but someone has to say that **this is a terrible programming style** to return the file context if the file exists or error string if not exists.

In this case, there is no error handling, the function always returns successful completion and instead of the person seeing the context of the template, he sees the error line (for example, open /some/path/some_file.some_extension: no such file or directory).

Instead of that, you shall use something like that:
```
func (x *xtpl) tplSource(tplPath string) (string, error) {
	b, err := ioutil.ReadFile(viewsPath + "/" + tplPath + "." + viewExtension)
        return string(b), err
}
```

and then handle errors at call points, for example (by the way, bad one, because of no errors handling, see next explaintations):

```
func xtplInit(tplPath string) *xtpl {
	var xTpl = &xtpl{}
	src, err := xTpl.tplSource(tplPath)
        if err == nil {
            return nil
        }
	xTpl.parse(src)
	return xTpl
}
```
Second terrible thing is almost no error handling at all (at least in the file). Errors must be checked at every step.

Next one, for example this code doesn't look good:

```
func xtplInit(tplPath string) *xtpl {
	var xTpl = &xtpl{}
	src := xTpl.tplSource(tplPath)
	xTpl.parse(src)
	return xTpl
}
```
again, because of no error handling. This routine is called in many places and can lead to unpredictable results in case of no error handling.

You develop a great product, do it better every day!

**Comment by PavelVershinin** [comment]
@oripio Ох, я так понимаю, тут все владеют Русским языком, гораздо лучше нежели я Английским. Поэтому, прошу меня извинить, отвечу на Русском.
Большое вам спасибо, за разъяснение! Отсутствие обработки ошибок, это очень плохо, согласен! Но это же, всего-лишь, шаблонизатор, я думаю, что он и не должен никак обрабатывать ошибки, его задача заключается исключительно в том чтобы обработать то что можно обработать и сообщить верстальщику о проблеме, там где он (Верстальщик) допустил ошибку. Именно по этой причине, в этом пакете, ошибки никак не обрабатываются, а просто скидывается текст описания ошибки в вывод, чтобы верстальщик увидел сообщение о проблеме и её исправил.
Да и как эту ошибку тут обработать? Запаниковать, но бекенд разработчик, врядли будет рад, от того что ему фронт программу уронить может. Записать в лог, так фронт логи не читает, не факт, что он вообще знает об их существовании.
Но это, конечно, исключительно моё мнение!

**Comment by oripio** [comment]
>  Но это же, всего-лишь, шаблонизатор, я думаю, что он и не должен никак обрабатывать ошибки

По тем же причинам и программы "падают", ибо программисты не счиатют нужным обрабатывать ошибки :-)

Почему важно обрабатывать ошибки? Как минимум, потому что они могут быть. 
Даже если файл присутствует, абсолютно не факт, что Вы его прочитаете (например, при ошибках вида EPERM, EACCES, EAGAIN, EBADF, EBADFD, EBUSY, и т.д.) шаблонизатором. Тот же верстальщик будет недоумевать, почему файл есть, а выдается ошибка.

Я уже не говорю о безопасности, что если во время работы, случайно, файл просто пропадет на файловой системе (будет удален, например), то в html **вывалится полный путь на файловой системе**, включая все поддиректории и неприкрытый текст ошибки. В этом случае появляется уже положительный потенциал у потенциальных злоумышленников, простите за тафталогию. 

> Да и как эту ошибку тут обработать? Запаниковать, но бекенд разработчик, врядли будет рад, от того что ему фронт программу уронить может

Тут есть два варианта: плохой и хороший.
Плохой - да, запаниковать. Тогда "проблемы шерифа...", в общем, обработчик на стороне бэка.
Хороший - сортировать мух от котлет и выводить отдельно ошибку и полезную нагрузку (результат парсинга, например).

**Comment by PavelVershinin** [comment]
@oripio 
> в html вывалится полный путь на файловой системе, включая все поддиректории и неприкрытый текст ошибки

Хм, весьма убедительный довод, спасибо! 
Обязательно последую вашему совету и уберу ошибки из результата парсинга.
